id: I7D33CA03
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T09:23:04+00:00'
last_modified: '2022-06-07T21:05:50.290928+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG01601
  title: རྡོ་རྗེ་འཇིགས་བྱེད་ཀྱི་སྒོ་ནས་ཡེ་ཤེས་ཀྱི་ཁྲོ་བོ་བཅུའི་གཏོར་ཟློག་བྱ་ཚུལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    51FD:
      image_group_id: I00KG02905
      title: ''
      total_pages: 54
      order: 1
      base_file: 51FD.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
